name: github-actions-demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
    push:
        branches: [main]
jobs:
    explore-github-actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
            - run: |
                echo "Current location is $(pwd)"
                echo "Working directory is ${{ github.workspace }}"
            - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
            - name: List files in the repository
              run: |
                ls ${{ github.workspace }}
            - run: echo "ğŸ This job's status is ${{ job.status }}."
    job-1:
        runs-on: ubuntu-latest
        steps:
            - run: echo "first step of the job-1"
            - run: echo "second step of the job-1"
            - run: echo "third step of the job-1"
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        steps:
            - run: echo "first step of the job-2"
            - run: echo "second step of the job-2"
            - run: echo "third step of the job-2"
    job-3:
        runs-on: ubuntu-latest
        needs: job-2
        steps:
            - run: echo "first step of the job-3"
            - run: echo "second step of the job-3"
            - run: echo "third step of the job-3"
